"""empty message

Revision ID: 330843e641f3
Revises: ca0436fe0186
Create Date: 2025-11-01 20:19:10.069407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '330843e641f3'
down_revision: Union[str, Sequence[str], None] = 'ca0436fe0186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_features', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_track_features_user_id'), 'track_features', ['user_id'], unique=False)
    op.create_foreign_key(None, 'track_features', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track_features', type_='foreignkey')
    op.drop_index(op.f('ix_track_features_user_id'), table_name='track_features')
    op.drop_column('track_features', 'user_id')
    # ### end Alembic commands ###
