"""create track_features

Revision ID: 92c2788bfaba
Revises: df476e4f6ce1
Create Date: 2025-10-28 20:16:12.505270

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92c2788bfaba"
down_revision: Union[str, Sequence[str], None] = "df476e4f6ce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track_features",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_datetime_utc", sa.DateTime(), nullable=True),
        sa.Column("end_datetime_utc", sa.DateTime(), nullable=True),
        sa.Column("start_hour_of_day_utc", sa.Integer(), nullable=True),
        sa.Column("day_of_week_index", sa.Integer(), nullable=True),
        sa.Column("start_latitude_deg", sa.Float(), nullable=True),
        sa.Column("start_longitude_deg", sa.Float(), nullable=True),
        sa.Column("end_latitude_deg", sa.Float(), nullable=True),
        sa.Column("end_longitude_deg", sa.Float(), nullable=True),
        sa.Column(
            "start_area_identifier_approx",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("total_distance_kilometers", sa.Float(), nullable=True),
        sa.Column("straight_line_distance_kilometers", sa.Float(), nullable=True),
        sa.Column("path_sinuosity_ratio", sa.Float(), nullable=True),
        sa.Column(
            "route_curvature_category",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("total_elevation_gain_meters", sa.Float(), nullable=True),
        sa.Column("total_elevation_loss_meters", sa.Float(), nullable=True),
        sa.Column("elevation_gain_per_kilometer", sa.Float(), nullable=True),
        sa.Column("terrain_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_elapsed_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("total_moving_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("total_stopped_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("average_speed_kilometers_per_hour", sa.Float(), nullable=True),
        sa.Column("maximum_speed_kilometers_per_hour", sa.Float(), nullable=True),
        sa.Column("features_version", sa.Integer(), nullable=False),
        sa.Column("computed_at_utc", sa.DateTime(), nullable=False),
        sa.Column("source_format", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_track_features_day_of_week_index"),
        "track_features",
        ["day_of_week_index"],
        unique=False,
    )
    op.create_index(
        op.f("ix_track_features_route_curvature_category"),
        "track_features",
        ["route_curvature_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_track_features_start_area_identifier_approx"),
        "track_features",
        ["start_area_identifier_approx"],
        unique=False,
    )
    op.create_index(
        op.f("ix_track_features_start_hour_of_day_utc"),
        "track_features",
        ["start_hour_of_day_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_track_features_terrain_category"),
        "track_features",
        ["terrain_category"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_track_features_terrain_category"), table_name="track_features")
    op.drop_index(op.f("ix_track_features_start_hour_of_day_utc"), table_name="track_features")
    op.drop_index(
        op.f("ix_track_features_start_area_identifier_approx"),
        table_name="track_features",
    )
    op.drop_index(op.f("ix_track_features_route_curvature_category"), table_name="track_features")
    op.drop_index(op.f("ix_track_features_day_of_week_index"), table_name="track_features")
    op.drop_table("track_features")
    # ### end Alembic commands ###
